# Surmount stellar.toml
VERSION="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://api.domain.com/federation"
TRANSFER_SERVER="https://api.domain.com"
SIGNING_KEY="GB7MHMJ4RQS54TMKB2M4BQGVTZF36IAM6PYSEK7QIX7HXQ4LNYQCLPGQ"
HORIZON_URL="https://horizon.domain.com"
ACCOUNTS=[
"GB7MHMJ4RQS54TMKB2M4BQGVTZF36IAM6PYSEK7QIX7HXQ4LNYQCLPGQ",
"GCN5YGFV4H2OCO4GGYMOMHWKHUTRD3L7YU5HFUVD4TAQVTUX7I254XLB"
]

[DOCUMENTATION]
ORG_NAME="Surmount Foundation"
ORG_DBA="Surmount"
ORG_URL="https://pkrpng.github.io"
ORG_LOGO="https://pkrpng.github.io/Surmount128.png"
ORG_DESCRIPTION="Decentralized financial token with intrinsic value created by algorithmic trading in forex markets"
ORG_PHYSICAL_ADDRESS="Vanuatu"
ORG_TWITTER="@SRMTFoundation"
ORG_OFFICIAL_EMAIL="n/a"

[[PRINCIPALS]]
name="Peter Krejcar"
email="surmountadmin@surmounttoken.com"
twitter="@PK_SRMT"

[[CURRENCIES]]
code="SRM"
issuer="GB7MHMJ4RQS54TMKB2M4BQGVTZF36IAM6PYSEK7QIX7HXQ4LNYQCLPGQ"
display_decimals=2
name="Surmount"
desc="1 Surmount token may entitle the holder to XLM from the Surmount Foundation"
image="https://pkrpng.github.io/Surmount128.png"

